modLoader="javafml"
loaderVersion="[44,)"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_project_url}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="regions_unexplored"
    mandatory=true
    versionRange="NONE"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="addonslib"
    mandatory=true
    versionRange="[1.19.3-1.9,)"
    ordering="NONE"
    side="BOTH"