modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="${mod_project_url}"
logoFile="logo.png"
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forge_version_range}" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mysticsbiomes"
mandatory=false
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="addonslib"
mandatory=true
versionRange="[1.19-1.8,)"
ordering="AFTER"