modLoader="javafml"
loaderVersion="[37,)"

license="${mod_license}"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Addons/issues"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-modding-legacy"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="addonslib"
mandatory=true
versionRange="[1.17.1-1.6,)"
ordering="AFTER"

[[dependencies.${mod_id}]]
modId="structure_gel"
mandatory=true
versionRange="NONE"
ordering="AFTER"