modLoader="javafml"
loaderVersion="[40,)"

license="${mod_license}"
issueTrackerURL="${mod_issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_project_url}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="regions_unexplored"
    mandatory=true
    versionRange="NONE"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="addonslib"
    mandatory=true
    versionRange="[1.18.2-1.10,)"
    ordering="AFTER"

[[dependencies.${mod_id}]]
    modId="modernfix"
    mandatory=true
    versionRange="NONE"
    ordering="AFTER"

