modLoader="javafml"
loaderVersion="[40,)"

license="${mod_license}"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Addons/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-byg-bwg"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="byg"
    mandatory=true
    versionRange="NONE"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="addonslib"
    mandatory=true
    versionRange="[1.18.2-1.8,)"
    ordering="BEFORE"
    side="BOTH"